import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-add-location',
  templateUrl: './add-location.page.html',
  styleUrls: ['./add-location.page.scss'],
})
export class AddLocationPage implements OnInit {
  data = {
    locationId: 0,
    refReferenceListCityId: 0,
    refReferenceListStateId: 0,
    refReferenceListCountryId: 0,
    isActive: true,
    isDeleted: true,
    refCreatedBy: 0,
    createdDate: '2023-04-03T12:10:15.660Z',
    refModifiedBy: 0,
    modifiedDate: '2023-04-03T12:10:15.660Z',
    address1: 'string',
    address2: 'string',
    address3: 'string',
    address4: 'string',
    pin: 'string',
    refCreatedByNavigation: {
      userId: 0,
      refOrgid: 0,
      isActive: true,
      refCreatedBy: 0,
      createdDate: '2023-04-03T12:10:15.660Z',
      refModifiedBy: 0,
      modifiedDate: '2023-04-03T12:10:15.660Z',
      userName: 'string',
      email: 'string',
      mobileNo: 'string',
      password: 'string',
      processing: 'string',
      comments: 'string',
      passwordHash: 'string',
      passwordSalt: 'string',
      emailVerified: true,
      isDeleted: true,
      refOrg: 'string',
    },
    refModifiedByNavigation: {
      userId: 0,
      refOrgid: 0,
      isActive: true,
      refCreatedBy: 0,
      createdDate: '2023-04-03T12:10:15.660Z',
      refModifiedBy: 0,
      modifiedDate: '2023-04-03T12:10:15.660Z',
      userName: 'string',
      email: 'string',
      mobileNo: 'string',
      password: 'string',
      processing: 'string',
      comments: 'string',
      passwordHash: 'string',
      passwordSalt: 'string',
      emailVerified: true,
      isDeleted: true,
      refOrg: 'string',
    },
    refReferenceListCity: {
      referenceListId: 0,
      refOrgId: 0,
      refReferenceId: 0,
      isActive: true,
      isDeleted: true,
      refCreatedBy: 0,
      createdDate: '2023-04-03T12:10:15.660Z',
      refModifiedBy: 0,
      modifiedDate: '2023-04-03T12:10:15.660Z',
      name: 'string',
      description: 'string',
      refCreatedByNavigation: 'string',
      refModifiedByNavigation: 'string',
      refOrg: 'string',
      refReference: {
        referenceId: 0,
        isActive: true,
        isDeleted: true,
        refCreatedBy: 0,
        createdDate: '2023-04-03T12:10:15.660Z',
        refModifiedBy: 0,
        modifiedDate: '2023-04-03T12:10:15.660Z',
        name: 'string',
        description: 'string',
        refOrgId: 0,
        refCreatedByNavigation: 'string',
        refModifiedByNavigation: 'string',
        refOrg: 'string',
      },
    },
    refReferenceListCountry: {
      referenceListId: 0,
      refOrgId: 0,
      refReferenceId: 0,
      isActive: true,
      isDeleted: true,
      refCreatedBy: 0,
      createdDate: '2023-04-03T12:10:15.660Z',
      refModifiedBy: 0,
      modifiedDate: '2023-04-03T12:10:15.660Z',
      name: 'string',
      description: 'string',
      refCreatedByNavigation: 'string',
      refModifiedByNavigation: 'string',
      refOrg: 'string',
      refReference: {
        referenceId: 0,
        isActive: true,
        isDeleted: true,
        refCreatedBy: 0,
        createdDate: '2023-04-03T12:10:15.660Z',
        refModifiedBy: 0,
        modifiedDate: '2023-04-03T12:10:15.660Z',
        name: 'string',
        description: 'string',
        refOrgId: 0,
        refCreatedByNavigation: 'string',
        refModifiedByNavigation: 'string',
        refOrg: 'string',
      },
    },
    refReferenceListState: {
      referenceListId: 0,
      refOrgId: 0,
      refReferenceId: 0,
      isActive: true,
      isDeleted: true,
      refCreatedBy: 0,
      createdDate: '2023-04-03T12:10:15.660Z',
      refModifiedBy: 0,
      modifiedDate: '2023-04-03T12:10:15.660Z',
      name: 'string',
      description: 'string',
      refCreatedByNavigation: 'string',
      refModifiedByNavigation: 'string',
      refOrg: 'string',
      refReference: {
        referenceId: 0,
        isActive: true,
        isDeleted: true,
        refCreatedBy: 0,
        createdDate: '2023-04-03T12:10:15.660Z',
        refModifiedBy: 0,
        modifiedDate: '2023-04-03T12:10:15.660Z',
        name: 'string',
        description: 'string',
        refOrgId: 0,
        refCreatedByNavigation: 'string',
        refModifiedByNavigation: 'string',
        refOrg: 'string',
      },
    },
  };
  constructor() {}

  ngOnInit() {}
}
